[versions]
kotlinpoet = "1.12.0"
compiletesting = "1.4.9"

[libraries]
compiletesting-kt = { module = "com.github.tschuchortdev:kotlin-compile-testing", version.ref = "compiletesting" }
compiletesting-ksp = { module = "com.github.tschuchortdev:kotlin-compile-testing-ksp", version.ref = "compiletesting" }
inject = "javax.inject:javax.inject:1"
junit4 = "junit:junit:4.13-beta-3"
kotlinpoet-core = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }
ksp = "com.google.devtools.ksp:symbol-processing-api:1.7.0-1.0.6"
tp = "com.github.stephanenicolas.toothpick:toothpick:3.1.0"
